### PR TITLE
Add WeightLog handler for saving weights and changes into a CSV file

### PR DESCRIPTION
**Pull request by dnouri**

### CODE REVIEW

**Comment by cancan101** [comment]
Would it make sense to have some way of deferring the write to out on epoch end rather than writing out each batch?

**Comment by dnouri** [comment]
> Would it make sense to have some way of deferring the write to out on epoch end rather than writing out each batch?

@cancan101 You worried your SSD will break?

**Comment by cancan101** [comment]
and related, does it makes sense to keep the file open (and perhaps the  `DictWriter`), rather than open and closing the file? You can always call `flush` if you are scared of losing data.

**Comment by dnouri** [comment]
@cancan101 Thanks for the feedback. Addressed the issues. Now keeping file open throughout. Also buffering.

**Pull request merged**
