### PR TITLE
Network.predict works with multi-outputs

### PR DESCRIPTION
**Pull request by DanChianucci**
The initialize layers test are failing because I modified it so that it returned a list of the output layers rather than a single layer.  

Suggestions on how to proceed?

We could have it return a single Layer if only one output is defined, and a list of Layers if multiple are defined.  Internally I could set the protected `_output_layers` variable which is needed later on.

### CODE REVIEW

**Comment by DanChianucci** [comment]
Issue #157 is related to this

**Comment by dnouri** [comment]
Sorry for a late reply.  I think it's fine changing `initialize_layers` to always return a list of outputs.

**Comment by DanChianucci** [comment]
As of the latest commit in this PR, `initialize_layers` returns a single layer if there is only one output layer, otherwise it returns a list of output layers.   That way, old code which doesn't expect to get a list will continue working.  

I can change it so that it always returns a list, which will make the behavior consistent, but break older code that might rely on the current implementation.  So its  kind of a trade-off.

**Comment by BenjaminBossan** [comment]
The current solution seems to be fine by me (although I can imagine that `initialze_layers` is rarely customized, therefore making backwards compatibility less important).

**Comment by dnouri** [comment]
Yeah I have a feeling it's better returning a list always.
 
I don't expect *anyone* will have `initialize_layers` customized; it's pretty obscure.  If they did, they'll deal with it.

**Comment by dnouri** [comment]
@DanChianucci Can you rebase from master and fix those two test errors? Thanks.

**Pull request closed without merging**
