### PR TITLE
Allow loading weights with shape mismatch

### PR DESCRIPTION
**Pull request by cancan101**

### CODE REVIEW

**Comment by dnouri** [comment]
It's not clear to me why this is useful.  And what the strategy would be of loading weights when there's a shape mismatch.  What assumptions are we making and why.

**Comment by cancan101** [comment]
This allows loading pre trained weights into a network where the number of convolutional filters for a given layer has grown.

e.g. I train a CNN with 16 filters for a given layer and I now want to load those weights into a network where I have incremented the number of filters to 32.

**Comment by dnouri** [comment]
Okay.  I assume you tried it and it works better in your case than training from scratch?

Honestly I haven't encountered this idea anywhere before.  Is there literature or a mention of this method elsewhere?

**Comment by dnouri** [comment]
I feel like this is too special a use case to add it to the library.  I'd encourage you to move the weights loading algorithm as a function inside your own application code.  Let me know if for some reason that isn't a good alternative.

**Pull request closed without merging**
