### PR TITLE
Feature visualization

### PR DESCRIPTION
**Pull request by dnouri**
(Supercedes #74)

Create new visualize.py and utils.py

Added some visualization functions for convenience:

    plot_loss: Plot train loss and valid loss
    plot_weights: Plot the filters of a convolutional layer
    plot_activity: Plot activity of a convolutional layer produced by a sample
    plot_occlusion: For image samples, shows which part of the images are crucial for the prediction

Requires a utility function:

    occlusion_heatmap: Creates a heatmap of where an occlusion affects the prediction

Tests only check whether plotting with different options does not raise an exception.

### CODE REVIEW

**Comment by dnouri** [comment]
@BenjaminBossan I tried fixing a matplotlib-related problem on Travis, but failed.  Maybe you could take a cool?

**Comment by BenjaminBossan** [comment]
I guess you found this one:
http://stackoverflow.com/a/3054314

The comment indicates that the .use call has to happen before the matplotlib import. How to do this for our case without changing the source of visualize I don't know.

**Comment by dnouri** [comment]
Yes, that's what I saw.  But there's no way to call `use` before the import, read again.

**Comment by BenjaminBossan** [comment]
As I said, I also don't see how to do it.

One could check how others do it:
https://github.com/matplotlib/matplotlib/blob/master/.travis.yml

Or just ignore this?

**Comment by dnouri** [comment]
No, what you said is call `matplotlib.use` *before* importing matplotlib.  ;-)

Any idea which lines of this travis file you're linking to is relevant?

**Comment by BenjaminBossan** [comment]
Unfortunately no idea, I have no experience with travis yet.

**Comment by BenjaminBossan** [comment]
I have an idea: matplotlib supports a config, matplotlibrc
http://matplotlib.org/users/customizing.html

In the config, you can set the backend. So something like this may work:
echo "backend : agg" > .config/matplotlib/matplotlibrc

**Pull request merged**
