### PR TITLE
Cast to floatX in functional toy tests

### PR DESCRIPTION
**Pull request by BenjaminBossan**

### CODE REVIEW

**Comment by dnouri** [comment]
Looks like this unearthed another bug?

**Comment by BenjaminBossan** [comment]
my guess is that floatX is not set properly

**Comment by dnouri** [comment]
Tried running these tests on CPU locally?

**Comment by BenjaminBossan** [comment]
yeah, that works fine for me.

**Comment by dnouri** [comment]
Then set floatX to 64 in your config.

**Comment by BenjaminBossan** [comment]
Then it fails.

**Comment by dnouri** [comment]
Right, it's the `fmatrix` used in NeuralNet that assumes `float32` for regression targets always.  Not sure if it's better to have that matrix be of type `floatX` instead?

**Comment by BenjaminBossan** [comment]
Not exactly sure I understand what you get at, but one should make sure to always have the same precision, since theano will cast to the higher precision otherwise, AFAIK.

**Comment by dnouri** [comment]
OK so then this line needs fixing:
https://github.com/dnouri/nolearn/blob/a5dfb25f9884eccaf9f107d761e5edf474e5ff04/nolearn/lasagne/base.py#L202

**Comment by BenjaminBossan** [comment]
I still don't get what you suggest, maybe you could just fix it if you have an idea?

**Comment by dnouri** [comment]
`T.fmatrix` means we're assuming float32 input.  Your PR unearthed this problem.

I see two options: 1) We fix production code in nolearn to not assume float32 as y's type on the way in.  2) We revert your changes to the tests to work with the assumption that all y regression data should be float32.  I think you said you prefer the former.  Which seems reasonable.

So what we need to do is get rid of that `T.fmatrix` and replace it by something that's the same type as floatX, so that we no longer have a hard-coded assumption that regression data has to be float32.

Hope that clarifies things?

**Comment by BenjaminBossan** [comment]
So I made a change which should correspond to your suggestion 1). When I switch to CPU + float64, the tests pass. Unfortunately, I could not devise a test that checks both, since the device cannot be changed at runtime. Do you have an idea?

I'm also wondering a little bit why the same error does not occur with T.imatrix in case of classification.

**Comment by dnouri** [comment]
Thanks!

Here's an alternative way to get that matrix type:
`y_tensor_type = T.TensorType(config.floatX, (False, False))`

Maybe that's better than the condition?

Don't have an idea on how to test the same thing for both float32 and 64, but I guess we're fine.

As far as `T.imatrix` is concerned: we're always explicitly casting to `int32` in the tests, so there's no case where precision is lost, and therefore no such error.

**Comment by BenjaminBossan** [comment]
So I changed the code according to your suggestion.

> Don't have an idea on how to test the same thing for both float32 and 64, but I guess we're fine.

One way to try both scenarios would then be to make sure to test nolearn on GPU and have Travis test the CPU part. I have no better idea right now.

> As far as T.imatrix is concerned: we're always explicitly casting to int32 in the tests, so there's no case where precision is lost, and therefore no such error.

So we are forcing users to use int32 when classifying but give them a choice when performing regression? That seems to be inconsistent.

**Comment by dnouri** [comment]
> So we are forcing users to use int32 when classifying but give them a choice when performing regression? That seems to be inconsistent.

We're not giving them a choice with regression, really.  We're saying: you have to use whatever is defined in floatX.  I'm actually not sure how much sense it makes to use/force int32 for a list of classes, or where I got the idea from even.

**Comment by BenjaminBossan** [comment]
What is the verdict, then, with int32?

**Comment by dnouri** [comment]
Let's leave that for another issue if you want.

But I think we could try int64 instead and see what happens (also if you still pass int32).

**Comment by BenjaminBossan** [comment]
But let's not do this here, it's a different issue, I'd say.

**Pull request merged**
